[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[logger]
level = "error"

[runner]
fastReruns = false

[client]
showErrorDetails = false