[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 7860
address = "0.0.0.0"
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 7860

[logger]
level = "error"

[client]
showErrorDetails = false

[theme]
base = "light"